name: Deploy Feature Environment
description: >
  Deploy Container Apps, HttpRouteConfig, and Front Door resources for a feature
  environment using main.bicep. Requires an active Azure CLI session.

inputs:
  feature_name:
    description: Feature environment name (e.g. feature-1234)
    required: true
  resource_group:
    description: Azure resource group for the deployment
    required: true
  registry_server:
    description: Container registry server URL (e.g. niscontainers.azurecr.io)
    required: true
  nordic_image_tag:
    description: Nordic container image tag
    required: true
  worker_image_tag:
    description: Worker container image tag
    required: true
  waf_policy_id:
    description: Resource ID of the WAF policy to associate
    required: true
  dns_zone_resource_group:
    description: Resource group containing the cust.nisportal.com DNS zone
    required: true
  user_managed_identity_name:
    description: Name of the user-assigned managed identity used for ACR pull access on the Container Apps
    required: true
  user_managed_identity_resource_group:
    description: Resource group where the user-assigned managed identity resides
    required: true
  app_config_name:
    description: Name of the Azure App Configuration resource
    required: true
  use_elastic8:
    description: Whether to enable Elastic 8 (true/false)
    required: false
    default: 'true'
  elastic8_endpoint:
    description: Elastic 8 endpoint URL (leave empty to disable)
    required: false
    default: ''
  has_custom_jwt_secret:
    description: Whether a custom JWT secret is configured in Key Vault for this environment (true/false)
    required: false
    default: 'false'
  container_apps_environment_name:
    description: Name of the shared Container Apps Environment
    required: false
    default: 'feature-environments'

outputs:
  feature_url:
    description: Full HTTPS URL of the deployed feature environment
    value: ${{ steps.deploy.outputs.feature_url }}
  fd_hostname:
    description: Front Door endpoint hostname (without https://) — pass to create-dns-cname
    value: ${{ steps.deploy.outputs.fd_hostname }}

runs:
  using: composite
  steps:
    - name: Ensure Container Apps Environment is running
      shell: bash
      run: |
        ENV_NAME="${{ inputs.container_apps_environment_name }}"
        RG="${{ inputs.resource_group }}"

        echo "Starting Container Apps Environment (no-op if already running)..."
        az containerapp env start \
          --name "$ENV_NAME" \
          --resource-group "$RG" 2>/dev/null || true
        echo "Container Apps Environment is ready."

    - name: Deploy to Azure
      id: deploy
      shell: bash
      run: |
        RESULT=$(az deployment group create \
          --name "deploy-${{ inputs.feature_name }}-$(date +%Y%m%d-%H%M%S)" \
          --resource-group "${{ inputs.resource_group }}" \
          --template-file "${{ github.action_path }}/main.bicep" \
          --parameters "${{ github.action_path }}/parameters/feature-environment.bicepparam" \
          --parameters \
            name="${{ inputs.feature_name }}" \
            registryServer="${{ inputs.registry_server }}" \
            nordicContainerImageName="${{ inputs.registry_server }}/nordic" \
            nordicContainerImageTag="${{ inputs.nordic_image_tag }}" \
            workerContainerImageName="${{ inputs.registry_server }}/worker" \
            workerContainerImageTag="${{ inputs.worker_image_tag }}" \
            appConfigLabel="Feature-$(echo '${{ inputs.feature_name }}' | sed 's/^feature-//')" \
            userManagedIdentityName="${{ inputs.user_managed_identity_name }}" \
            userManagedIdentityResourceGroup="${{ inputs.user_managed_identity_resource_group }}" \
            appConfigName="${{ inputs.app_config_name }}" \
            useElastic8="${{ inputs.use_elastic8 }}" \
            elastic8Endpoint="${{ inputs.elastic8_endpoint }}" \
            hasCustomJwtSecret="${{ inputs.has_custom_jwt_secret }}" \
            containerAppsEnvironmentName="${{ inputs.container_apps_environment_name }}" \
            wafPolicyId="${{ inputs.waf_policy_id }}" \
            dnsZoneResourceGroup="${{ inputs.dns_zone_resource_group }}" \
          --query 'properties.outputs' -o json)

        FD_URL=$(echo "$RESULT" | jq -r '.frontDoorUrl.value' | sed 's|https://||')
        echo "fd_hostname=$FD_URL" >> "$GITHUB_OUTPUT"
        echo "feature_url=$(echo "$RESULT" | jq -r '.featureUrl.value')" >> "$GITHUB_OUTPUT"
